export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_CUISINES = 'SET_CUISINES'
export const SET_RECIPE = 'SET_RECIPE'
export const SET_USER = 'SET_USER'
export const REMOVE_IMAGES = 'REMOVE_IMAGES'
export const ADD_IMAGES = 'ADD_IMAGES'
