export const SIGN_IN = 'SIGN_IN'
export const SIGN_OUT = 'SIGN_OUT'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_CUISINES = 'SET_CUISINES'
export const SET_RECIPE = 'SET_RECIPE'
export const REMOVE_RECIPES = 'REMOVE_RECIPES'
export const ADD_RECIPES = 'ADD_RECIPES'
export const SET_USER = 'SET_USER'
