export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'
export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_CUISINES = 'SET_CUISINES'
export const SET_RECIPE = 'SET_RECIPE'
export const SET_RECIPES = 'SET_RECIPES'
export const SET_USER = 'SET_USER'
